//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.Oduncler = new HashSet<Oduncler>();
        }
    
        public int kitapId { get; set; }
        public string kitapAdi { get; set; }
        public string kitapYazari { get; set; }
        public string kitapYayinEvi { get; set; }
        public Nullable<int> kitapStok { get; set; }
        public Nullable<int> kitapSayfa { get; set; }
        public string kitapTuru { get; set; }
        public Nullable<int> kitapBasimYili { get; set; }
        public string kitapDurum { get; set; }
        public string kitapBarkod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oduncler> Oduncler { get; set; }
    }
}
